### ISSUE TITLE
Unable to initialize Fingerprint sensor

### ISSUE THREAD

**Issue by gauravdave01** [bastianraschke/pyfingerprint#1]
I am using this library to connect R305 (ZFM60_BAK_V1.4). When I try to enroll a new finger, it gives this error:

```
The fingerprint sensor could not be initialized!
Exception message: The received packet do not begin with a valid header!
```

Instead of `/dev/ttyUSB0`, I'm doing `/dev/ttyAMA0` and Baud rate is: 9600 (I've tried with 115200 and 57600). But nothing works.

**Comment by bastianraschke** [comment]
Hey gauravdave01, you tried to exchange the data wires? Or used another computer, USB serial converter? Often this is the problem.

**Comment by gauravdave01** [comment]
Actually, I'm connecting the sensor with female-to-female jumper wires and then making a connection.

**Comment by Mehluko** [comment]
Did you find a way to fix this problem?

**Comment by bastianraschke** [comment]
Hey Mehluko, this is a really common problem. Mostly it is caused by bad wires or bad USB serial converter or baudrate. Anything else its hard to guess.

**Comment by gauravdave01** [comment]
Hey @Mehluko,

Please find steps which I've executed for integration:

So, I haven't used USB connector to make connection, I directly connected Fingerprint device with Raspeberry Pi 2's (Model B) GPIO.

This is how I have connected fingerprint device:

```
Black Wire ---- GPIO 6 [Ground]
White Wire ---- GPIO 15 [RX]
Green Wire ---- GPIO 8 [TX]
Red Wire ---- GPIO 1 [3V PWR]
```

I've tried these connection as well:
- Red wire to GPIO 2 [again 5V].
- Interchange RX connection with TX and vice versa.

I've made all the required basic changes, e.g. replaced ttyUSB0 with ttyAMA0 and other changes as described.

Still, I was getting error, then I tried with 52600 baud rate and it started _working!_.

I hope this could help.

**Comment by rubiagatra** [comment]
hello @gauravdave01, when I tried with 52600 I had this output

`stty: invalid argument ‘52600’
Try 'stty --help' for more information.
`

**Comment by Rajashri1234** [comment]
hi, I am getting same error 
The fingerprint sensor could not be initialized! 
Exception Message: The received packet do not begin with a valid header!

Did anyone find solution for this ?
I tried changing Tx & Rx connection. But it did not help
I am also making connections same as that of @gauravdave01 . Directly connecting Pi with sensor using female to male connection.

**Comment by EsEm17** [comment]
We have encountered this error:

Operation failed!
Exception message: storeTemplate() takes at least 2 arguments (1given)

Can you help us out? Pleease. Thank you.

**Comment by gauravdave01** [comment]
Hey @rubiagatra & @Rajashri1234,

Try running this command:

`@reboot sudo stty -F /dev/ttyAMA0 52600`

I think, this will change the default baudrate of **115200** to **52600**. Then try again with the connection I've describe before.

See, if that works.

**Comment by EsEm17** [comment]
We have encountered this error:
Operation failed!
Exception message: storeTemplate() takes at least 2 arguments (1given)
Can you help us out? Pleease. Thank you.

**Comment by philippmeisberger** [comment]
@EsEm17 please do not post your problem neither on closed nor opened issues that have nothing to do with it. If you tried your best and nothing helped open a new issue instead. Thank you

**Comment by EsEm17** [comment]
@philippmeisberger I don't know how okay I'll find ways. Thank you. I'm so sorry.

**Comment by brianmak3** [comment]
Hello, i manged to solve this problem by first changing the baud rate to 57600 as for my pi using this command line **sudo stty -F /dev/ttyAMA0 57600** then i interchanged the wires and it worked.

**Comment by Ashwinigunjal** [comment]
I am using  serial /dev/ttyS0 for communincation. it send packet successfully. but return invalid header. why this happen.

**Comment by Besomi996** [comment]
hello i tried the things that you proposed in here non has worked i thought maybe because i have FS-01 fingerprint sensor and i am using dev/ttyUSB0 please help me i cant make it work it keeps giving me the same error
The fingerprint sensor could not initialized
and i have followed all of the steps proposed here

**Comment by philippmeisberger** [comment]
Never heard about FS-01. Can you provide a datasheet? Probably the FS-01 is not compatible with PyFingerprint.

**Comment by Besomi996** [comment]
@philippmeisberger  yes of course you can find the manual here:
http://www.fingergo.cn/uploads/soft/FS-01_Fingerprint_Sensor_Manual_Download.pdf
I thought it is the problem but if doesnt work for these libraries then how does it work ?

**Comment by philippmeisberger** [comment]
I checked the datasheet: I am sorry but this library does not support the FS-01

**Comment by Besomi996** [comment]
@philippmeisberger I got the r308 and it still gives me the same error i cant find a way to fix it. If u can help me because i read this issue all of it and it didnt work

**Comment by philippmeisberger** [comment]
Please take a look at #44 and the FAQ (https://sicherheitskritisch.de/2015/03/fingerprint-sensor-fuer-den-raspberry-pi-und-debian-linux-en/)

**Comment by cjoshi015** [comment]
I have also encountered this problems

use this pin numbering

1 | 5V | Regulated 5V DC
2 | GND | Common Ground
3 | TXD | Data output - Connect to MCU RX
4 | RXD | Data Input - Connect to MCU TX
5 | TOUCH | Active Low output when there is touch on sensor by finger
6 | 3.3V | Use this wire to give 3.3V to sensor instead of 5V

and also check your jumber cables are connected properly or not majorly it is due to loose connection and on many sited pin number is given wrong use above pin numbers

I have solved my issue using above steps
