### ISSUE TITLE
Cannot debuild source file

### ISSUE THREAD

**Issue by justinpham0210** [bastianraschke/pyfingerprint#11]
Hi Everyone,
I face a problem when debuild the source file as below
Now signing changes and any dsc files...
 signfile python-fingerprint_1.4.dsc Philipp Meisberger <team@pm-codeworks.de>
gpg: directory `/home/pi/.gnupg' created
gpg: new configuration file `/home/pi/.gnupg/gpg.conf' created
gpg: WARNING: options in `/home/pi/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/home/pi/.gnupg/secring.gpg' created
gpg: keyring `/home/pi/.gnupg/pubring.gpg' created
gpg: skipped "Philipp Meisberger <team@pm-codeworks.de>": secret key not available
gpg: /tmp/debsign.8yIhsiew/python-fingerprint_1.4.dsc: clearsign failed: secret key not available
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1295:
running debsign failed

Does anybody can help me how to fix this?

Thanks in advance!
Justin

**Comment by philippmeisberger** [comment]
Hello @justinpham0210. This has already been discussed in #8 and is therefore a duplicate.
