### ISSUE TITLE
Importer cannot find module named utilities

### ISSUE THREAD

**Issue by ijm329** [bastianraschke/pyfingerprint#17]
Hello, I just cloned this project today and followed all of the installation instructions and whatnot. However, when I try to run any of the examples I get the following error: 

`Traceback (most recent call last):
  File "/usr/share/doc/python-fingerprint/examples/example_enroll.py", line 14, in <module>
    from pyfingerprint.pyfingerprint import PyFingerprint
  File "build/bdist.linux-armv6l/egg/pyfingerprint/pyfingerprint.py", line 14 , in <module>
ImportError: No module named utilities`

How do I go about fixing this? I've attempted to add the working directory to the python path, but that doesn't seem to work either.

**Comment by philippmeisberger** [comment]
Hello @ijm329. Which Python version are you using? It seems that you are using Python3. PyFingerprint 1.4 only supports Python2. We are currently working on the next release which will support Python3.

**Comment by bastianraschke** [comment]
Please test with newest Development @ijm329

**Comment by bastianraschke** [comment]
Should be fixed. I close the issue cause of any reaction.
