### ISSUE TITLE
After using setAddress() sensor will ignore any command

### ISSUE THREAD

**Issue by philippmeisberger** [bastianraschke/pyfingerprint#19]
Internal cached address is not updated so old address is used in following commands. This provokes the sensor to ignore commands.

**Comment by bastianraschke** [comment]
Thanks. Can we fix it when we update the `__address` field?

**Comment by philippmeisberger** [comment]
It is a possible bug, not an actual issue. I tried the following on my ZFM-20:

```
from pyfingerprint.pyfingerprint import PyFingerprint

f = PyFingerprint('/dev/ttyUSB0', 57600, 0xFFFFFFFF, 0x00000000)

if ( f.verifyPassword() == False ):
    raise ValueError('The given fingerprint sensor password is wrong!')

f.setAddress(0xFFFFFFFE)
f.readImage()

## Reset address to default
f.setAddress(0xFFFFFFFF)
```

Sensor still accepts the old address and `readImage()` is executed like expected (light turns on). But other models of ZhianTec (e.g. ZFM-60) may behave different. For convience: Update the `__address` field.
