### ISSUE TITLE
After using setPassword() sensor will ignore any command

### ISSUE THREAD

**Issue by philippmeisberger** [bastianraschke/pyfingerprint#20]
Internal cached password is not updated so old password is used in following commands. This provokes the sensor to ignore commands.

**Comment by bastianraschke** [comment]
Thanks. Can we fix it when we update the `__password` field and manual call `verifyPassword()`?

**Comment by philippmeisberger** [comment]
Yes, but calling `verifyPassword()` is not necessary

**Comment by philippmeisberger** [comment]
Shall I push change on Development branch?

**Comment by philippmeisberger** [comment]
It is a possible bug, not an actual issue. I tried the following on my ZFM-20:

```
from pyfingerprint.pyfingerprint import PyFingerprint

f = PyFingerprint('/dev/ttyUSB0', 57600, 0xFFFFFFFF, 0x00000000)

if ( f.verifyPassword() == False ):
    raise ValueError('The given fingerprint sensor password is wrong!')

f.setPassword(0x00000001)
f.readImage()

## Reset password to default
f.setPassword(0x00000000)
```

Sensor still accepts the old password and `readImage()` is executed like expected (light turns on). But other models of ZhianTec (e.g. ZFM-60) may behave different. For convience: Update the `__password` field.
