### ISSUE TITLE
Not working with ubuntu

### ISSUE THREAD

**Issue by graaj** [bastianraschke/pyfingerprint#22]
When I am running with this library on Ubuntu, I am getting 'The fingerprint sensor could not be initialized'. Have anyone faced this type of issue and find out the solution.

**Comment by bastianraschke** [comment]
Please check out the FAQ on my article: https://sicherheitskritisch.de/2015/03/fingerprint-sensor-fuer-den-raspberry-pi-und-debian-linux-en/
