### ISSUE TITLE
Exception message: 'module' object hribute 'Serial'

### ISSUE THREAD

**Issue by suchit111** [bastianraschke/pyfingerprint#24]
The fingerprint sensor could not be initialized!
Exception message: 'module' object has no attribute 'Serial'
Sir, 
we have encountered this error. We are using R305 module and running it with pi 3. Please respond.
Thank you.

**Comment by bastianraschke** [comment]
You need to install pySerial:
`$ sudo apt install python-serial `

**Comment by ffleandro** [comment]
I have successfully used with both ZFM-100 and R303.
If you're using pip and some kind of virtual environment, install `pyserial` instead of `serial`.
