### ISSUE TITLE
Works with R303

### ISSUE THREAD

**Issue by ffleandro** [bastianraschke/pyfingerprint#25]
I have successfully tested this library with no modifications using the scanner module [R303](https://www.dropbox.com/sh/orprmb3bgb6lqb6/AABJrv83ZyzCKCYFGlcjigi0a/User%20Manual%20for%20Fingerprint%20Module?dl=0&preview=R303+fingerprint+module+user+manual.pdf).

I guess it's compatible with the whole `R3xx` Scanner series.

**Comment by bastianraschke** [comment]
Okay nice to know. Where did you buy the sensor?

**Comment by ffleandro** [comment]
I imported it from AliExpress: https://www.aliexpress.com/item/R303-Capacitive-Fingerprint-Reader-Module-Sensor-Scanner/32620290283.html
