### ISSUE TITLE
Template delete counts from 0 & templates indexes start with 1

### ISSUE THREAD

**Issue by phgachoud** [bastianraschke/pyfingerprint#30]
When consulting the templates count with getTemplateCount() the total amount is given. Should'nt the deleteTemplate() function delete the first template with index (parameter) 1 do instead of 0?

**Comment by philippmeisberger** [comment]
No ;) The first template index is 0 not 1. `getTemplateCount()` returns the number of all templates like when using `len()` on lists. It is the same there.
