### ISSUE TITLE
uploadimage function

### ISSUE THREAD

**Issue by heshamhanafyh95** [bastianraschke/pyfingerprint#35]
i need uploadimage function can anyone help me

**Comment by philippmeisberger** [comment]
Duplicate of #33

**Comment by phgachoud** [comment]
can't you deal with characteristics strings instead??

**Comment by phgachoud** [comment]
Did you take a look @ the documentation on page 8 point 4.1.1 https://github.com/adafruit/Adafruit-Fingerprint-Sensor-Library/blob/master/documentation/ZFM-20_Fingerprint_Module.pdf and p.16-17

**Comment by bastianraschke** [comment]
Because of no responses, i close the issue now.
