### ISSUE TITLE
How to store fingerprint templates in database

### ISSUE THREAD

**Issue by prabhakaran4920** [bastianraschke/pyfingerprint#40]
Hi,
R305 is only capable for storing 256 templates, I want to store more templates . So i planed to store fingerprint  templates in database. But I don't know how to do that... can anyone help me do that..

**Comment by philippmeisberger** [comment]
Take a look at `example_enroll.py`: Let the sensor create the template for you https://github.com/bastianraschke/pyfingerprint/blob/0432a92251c1b88fae3e265a07c5c5c9cf76b438/src/files/examples/example_enroll.py#L69 but instead of storing it with `storeTemplate()` https://github.com/bastianraschke/pyfingerprint/blob/0432a92251c1b88fae3e265a07c5c5c9cf76b438/src/files/examples/example_enroll.py#L72 use `downloadCharacteristics()` to download and store it locally. For comparing two templates you must first upload them using `uploadCharacteristics()` and use `compareCharacteristics()`. Could possibly work.

**Comment by chimenk** [comment]
Hello,

I'm saving the downloaded characteristics into MySQL text column. When i try to upload those characteristics like this :

`f.uploadCharacteristics(0x02, chr)`

The chr variable is returned value from MySQL which contains the characteristics, this give me error "cannot convert argument to integer".  And when i cast the chr variable to integer then this error is shown "invalid literal for int() with base 10".

Any suggestion? i think i'm doing something wrong here.


---------------------------------------------------------
Updated:
After reading this [https://sicherheitskritisch.de/2015/03/fingerprint-sensor-fuer-den-raspberry-pi-und-debian-linux-en/](url) i can upload and finally compare the characteristics. Only need to add eval function. Thanks

**Comment by bastianraschke** [comment]
So it seems resolved - i close it.

**Comment by aidar13** [comment]
> Hello,
> 
> I'm saving the downloaded characteristics into MySQL text column. When i try to upload those characteristics like this :
> 
> `f.uploadCharacteristics(0x02, chr)`
> 
> The chr variable is returned value from MySQL which contains the characteristics, this give me error "cannot convert argument to integer". And when i cast the chr variable to integer then this error is shown "invalid literal for int() with base 10".
> 
> Any suggestion? i think i'm doing something wrong here.
> 
> Updated:
> After reading this [https://sicherheitskritisch.de/2015/03/fingerprint-sensor-fuer-den-raspberry-pi-und-debian-linux-en/](url) i can upload and finally compare the characteristics. Only need to add eval function. Thanks

Link not a work anymore. Can you describe in more detail what you did to upload templates to the scanner, or can you provide your code?

**Comment by adityadate1997** [comment]
I want to download and store the template in my server datatabase, I am using NodeMCU and Php with mysql on server side. This function is not provided in the library. Can anybody please guide me on this?

**Comment by philippmeisberger** [comment]
https://sicherheitskritisch.de/2015/03/fingerprint-sensor-fuer-den-raspberry-pi-und-debian-linux-en/

**Comment by nguyenhaibien** [comment]
> https://sicherheitskritisch.de/2015/03/fingerprint-sensor-fuer-den-raspberry-pi-und-debian-linux-en/

hello! 
I'm using RPi3 and R308 sensor to execute example_search.py but it alway return Exception error: Communicate error
and fail at this line:
 characterics = str(f.downloadCharacteristics(0x01)).encode('utf-8')
please help me to fix it :( thank you

**Comment by philippmeisberger** [comment]
> > https://sicherheitskritisch.de/2015/03/fingerprint-sensor-fuer-den-raspberry-pi-und-debian-linux-en/
> 
> hello!
> I'm using RPi3 and R308 sensor to execute example_search.py but it alway return Exception error: Communicate error
> and fail at this line:
> characterics = str(f.downloadCharacteristics(0x01)).encode('utf-8')
> please help me to fix it :( thank you

Please see #44

**Comment by nguyenhaibien** [comment]
Hi!
Many thanks for replying to my comment, I will follow your instructions
(Sorry for the late reply and my English is everage)

Vào Th 6, 12 thg 6, 2020 vào lúc 22:47 Philipp Meisberger <
notifications@github.com> đã viết:

**Comment by inayatku** [comment]
> Hello,
> 
> I'm saving the downloaded characteristics into MySQL text column. When i try to upload those characteristics like this :
> 
> `f.uploadCharacteristics(0x02, chr)`
> 
> The chr variable is returned value from MySQL which contains the characteristics, this give me error "cannot convert argument to integer". And when i cast the chr variable to integer then this error is shown "invalid literal for int() with base 10".
> 
> Any suggestion? i think i'm doing something wrong here.
> 
> Updated: After reading this [https://sicherheitskritisch.de/2015/03/fingerprint-sensor-fuer-den-raspberry-pi-und-debian-linux-en/](url) i can upload and finally compare the characteristics. Only need to add eval function. Thanks

I think this issue is resolved . But the information  is a bit scattered. Plz let me know the actual instructions to do so. If possible plz share a sample python code to upload and download fingerprint characteristic from mysql database.  Your help would be much appreciated.
