### ISSUE TITLE
Same fingerprint on different fingerprint sensors

### ISSUE THREAD

**Issue by majidalaeinia** [bastianraschke/pyfingerprint#42]
I am using R303 fingerprint sensor and it works properly with the library. **I have a database table for the fingerprints, and each fingerprint is stored in the database with the related fields.**

I want to use another R303 sensor, and not to `enroll` the old finger into the new sensor. I mean to enroll a fingerprint in one sensor and be able to find the exact fingerprint by the new sensor.

I have read all the issues already and seems there's no upload function. Should I use [uploadCharacteristics](https://github.com/bastianraschke/pyfingerprint/blob/86a7a132263c53e2edef9be6223fe81f29be9192/src/files/pyfingerprint/pyfingerprint.py#L1126) function? Is there any method or property in the library, that can help me with this?

**Comment by philippmeisberger** [comment]
Download characteristics from sensor 1 using `downloadCharacteristics()` and upload them to sensor 2 using `uploadCharacteristics()`. After that store the uploaded template using `storeTemplate()` on sensor 2. Not tested but could possibly work.

**Comment by majidalaeinia** [comment]
I will share the results, as soon as I buy the new sensor and test those methods.

**UPDATE:**
It works. Thanks.
Here is an example to copy template position #0 to the template position #50, on the **current fingerprint sensor**:
```python
# Suppose that `old_position_number` already is a stored template and `new_position_number`
# is an empty template position
old_position_number = 0
new_position_number = 50
f.loadTemplate(old_position_number, 0x01)
characterics_old = str(f.downloadCharacteristics(0x01)).encode('utf-8')
f.uploadCharacteristics(0x02, f.downloadCharacteristics(0x01))
f.storeTemplate(new_position_number, 0x02)
```
NOTE:
I was not able to find a new R303 fingerprint sensor, even on online stores in Iran. So I used the current sensor to test the issue.
