### ISSUE TITLE
Fingerprint Recognition algorithm design 

### ISSUE THREAD

**Issue by hackerman13-0** [bastianraschke/pyfingerprint#47]
Hi i just wanted to know how i can design my own fingerprint recognition algorithm and what important things i should take into account while doing so. It would be great if you could help me out. Thanks in advance :D

**Comment by philippmeisberger** [comment]
Hello,
this library just uses the fingerprint recognition implementation of the fingerprint sensor. We have only basically understanding of fingerprint image processing. To see a real fingerprint processing algorithm take a look at https://www.nist.gov/services-resources/software/nist-biometric-image-software-nbis
