### ISSUE TITLE
SerialException: could not open port 'COM3' WindowsError(5, 'Access is denied')

### ISSUE THREAD

**Issue by TehseenHasan** [bastianraschke/pyfingerprint#54]
I am using **two** R305 fingerprint sensors with this pyFingerprint library (Python 2.7) on Windows PC using CH340 USB-to-Serial Converters. I am using this library to just download fingerprint image from sensor to PC. I have set baudrate of sensors to 960000 bps and its working fine. Sensors are working and giving me the fingerprint images fast and correctly... But sometimes suddenly one of my sensor stop working and its LED light is turned off and this exception message is shown: **SerialException: could not open port 'COM3' WindowsError(5, 'Access is denied')**.

**This is my code:**
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
PyFingerprint
Copyright (C) 2015 Bastian Raschke <bastian.raschke@posteo.de>
All rights reserved.

"""

from time import sleep
from pyfingerprint import PyFingerprint

port = 'COM3'
baudrate = 960000

print "Fingerprint Searching Started..."

## Reads image and download it
while (True):
    ## Tries to initialize the sensor
    try:
        f = PyFingerprint(port, baudrate, 0xFFFFFFFF, 0x00000000)

        if ( f.verifyPassword() == False ):
            raise ValueError('The given fingerprint sensor password is wrong!')

    except Exception as e:
        print('The fingerprint sensor could not be initialized!')
        print('Exception message: ' + str(e))
        sleep(1)
        continue

    while (True):
        ## Tries to read image and download it
        try:
            ## Wait that finger is read
            while ( f.readImage() == False ):
                pass
            imageDestination =  'C:\\Users\\Tehseen\\Desktop\\temp.bmp'
            f.downloadImage(imageDestination)

            print('The image was saved to "' + imageDestination + '".')

        except Exception as e:
            print('Operation failed!')
            print('Exception message: ' + str(e))
            break
            
        sleep(0.5)
```
**What I tried:**
I tried these things but error remains

- change baudrate of sensor to 115200, 57600, or 9600 bps
- close and run this code (script) again when the error occurred but sensor did not respond and error remains.
- Run this script using Administrator privileges by using **Run as Administrator** but again that error occurred.

**The only solution that works** is to **Unplug and plug again** the USB-to-Serial converter to USB port of my PC. After that this script start working correctly.... **but** after some **random time** the error occurred again.

Is this error is related to hardware or code of the library.??? I searched a lot about that issue and tried to solve this but nothing successful... Is there any way to reset the power (turn power on and off) of the USB port using python.? or reset the fingerprint sensor using this pyFingerprint library.? How to solve this... Thanks...

**Comment by philippmeisberger** [comment]
I think that this is not a problem of PyFingerprint but rather a driver or hardware problem

**Comment by TehseenHasan** [comment]
Issue **solved**... I just **changed the USB extension cable** that I used between USB-to-Serial converter and PC... So it was hardware related issue.... Thanks...!
