### ISSUE TITLE
Optical Finger Print reader R307 - The received packet do not begin with a valid header!

### ISSUE THREAD

**Issue by anubhaw2091** [bastianraschke/pyfingerprint#55]
Am using R307 finger print reader but am not able to get it up and running.

```
pi@raspberrypi:/usr/share/doc/python-fingerprint/examples $ python ./example_index.py 
The fingerprint sensor could not be initialized!
Exception message: The received packet do not begin with a valid header!
```

I have read almost all the posts and am not able to find any solution. I ran the same R307 module with the Arduino and used the same jumper cables, so I can say that hardware and wires are not at fault.

Followed all the parts of this [tutorial](https://sicherheitskritisch.de/2015/03/fingerprint-sensor-fuer-den-raspberry-pi-und-debian-linux-en/) and even went through the "Update 7" which deals with the raspberry situation. Nothing seems to work out. Any leads will be highly appreciated.

**Comment by sand007man** [comment]
Are your using ttyUSB0 or ttyAMA0???? if its USB-serial then which one are you using??

**Comment by anubhaw2091** [comment]
Am using ttyUSB0.
