### ISSUE TITLE
R307 Fingerprint Sensor Error - The received packet do not begin with a valid header!

### ISSUE THREAD

**Issue by varun9597** [bastianraschke/pyfingerprint#56]
I have connected R307 to Raspberry Pi using Serial to USB Adapter. My connections are as follows:
Red Wire (5V)-----> +5V on Serial to USB
Black Wire (GND)-----> GND on Serial to USB
Yellow Wire (TXD) -----> TXD on Serial to USB
White Wire (RXD) ------> RXD on Serial to USB

Here is the code that i am using-
[test.txt](https://github.com/bastianraschke/pyfingerprint/files/2717804/test.txt)

I am getting the following error:
Exception message: The received packet do not begin with a valid header!

**Comment by philippmeisberger** [comment]
Possible duplicate. Please see #55, #52 and #1
