### ISSUE TITLE
Can this library be used on MacOs Mojave

### ISSUE THREAD

**Issue by anubhaw2091** [bastianraschke/pyfingerprint#58]
Hey.

I was wondering if this library can be used on MacOs Mojave? I mean what changes should be done on the following line?

`f = PyFingerprint('/dev/ttyUSB0', 57600, 0xFFFFFFFF, 0x00000000)`

Thanks

**Comment by ardawan** [comment]
> `f = PyFingerprint('/dev/ttyUSB0', 57600, 0xFFFFFFFF, 0x00000000)`

disconnect your sensor from the USB and do ``` $ ls /dev/ ```
then connect the sensor to the USB and redo ``` $ ls /dev/ ```

if you found any new item in the list, that will be replace with the ```'/dev/ttyUSB0'``` . The rest is all about your sensor.

**Comment by bastianraschke** [comment]
Thanks for your aswer @ardawan, i close the issue.
