### ISSUE TITLE
uploadImage implementation

### ISSUE THREAD

**Issue by mefsantos** [bastianraschke/pyfingerprint#62]
Since i'm kinda new in community projects and cannot figure out how to send you the code, i'll leave the implementation here. I tested it (not thoroughly though) but it works. I also added the two missing commands for the purpose.

FYI: i'm far from being a pro on programming this close to sensors but i used uploadCharacteristics and downloadImage as references for this code. 

`
import numpy
FINGERPRINT_UPLOADIMAGE = 0x0B
FINGERPRINT_ERROR_UPLOADIMAGE = 0x0E

    def uploadImage(self, imageLocation):
        """
        Upload the image of a finger from host computer.

        @param string imageLocation
        @return void
        """
        locationDirectory = os.path.dirname(imageLocation)
        if not os.access(locationDirectory, os.R_OK):
            raise ValueError('The given location directory "' + locationDirectory + '" is not readable!')

        if not os.path.exists(imageLocation):
            raise ValueError('File "' + imageLocation + '" does not exist!')

        maxPacketSize = self.getMaxPacketSize()

        print("Sending first packet to upload image...") # debug
        packetPayload = (
            FINGERPRINT_UPLOADIMAGE,
        )

        self.__writePacket(FINGERPRINT_COMMANDPACKET, packetPayload)

        ## Get first reply packet
        receivedPacket = self.__readPacket()

        receivedPacketType = receivedPacket[0]
        receivedPacketPayload = receivedPacket[1]

        if receivedPacketType != FINGERPRINT_ACKPACKET:
           raise Exception('The received packet is no ack packet!')
        # DEBUG: The sensor will send follow-up packets
        if receivedPacketPayload[0] == FINGERPRINT_OK:
            pass
        elif receivedPacketPayload[0] == FINGERPRINT_ERROR_COMMUNICATION:
            raise Exception('Communication error')
        elif receivedPacketPayload[0] == FINGERPRINT_ERROR_UPLOADIMAGE:
            raise Exception('Could not upload image')
        else:
            raise Exception('Unknown error ' + hex(receivedPacketPayload[0]))

        imageToUpload = Image.open(imageLocation)
        imageArray = numpy.array(imageToUpload)

        maxRowLength = max(map(lambda x: len(x), imageArray))

        print("will start sending data packets")

        if maxRowLength <= maxPacketSize:
            print("sending 1 row of pixels at a time") # debug
            i = 1
            for i in range(0, len(imageArray)-1):
                self.__writePacket(FINGERPRINT_DATAPACKET, imageArray[i])
            self.__writePacket(FINGERPRINT_ENDDATAPACKET, imageArray[len(imageArray)-1])

        else:
            # we need to flatten the list of lists into a single list and divide
            print("flattening pixels arrays into a list and sending packets with length: " + str(maxPacketSize)) # debug
            flattenedList = list(imageArray.flatten())
            packetNbr = len(flattenedList) / maxPacketSize

            if packetNbr <= 1:
                print("Only one packet to send. Sending...") # debug
                self.__writePacket(FINGERPRINT_ENDDATAPACKET, flattenedList)
            else:
                print("Sending " + str(packetNbr) + " packets. This may take a while ...") # debug / info
                i = 1
                while i < packetNbr:
                    lfrom = (i-1) * maxPacketSize
                    lto = lfrom + maxPacketSize
                    self.__writePacket(FINGERPRINT_DATAPACKET, flattenedList[lfrom:lto])
                    i += 1
                    lfrom = (i-1) * maxPacketSize
                    lto = lfrom + maxPacketSize
                    
                self.__writePacket(FINGERPRINT_ENDDATAPACKET, flattenedList[lfrom:lto])
        print("Finished uploading image")
        # TODO (computation time drawback): download the image from buffer and compare with 'imageArray'        
`

**Comment by philippmeisberger** [comment]
Thanks for that but please create a pull request so that we can merge your changes ;)

**Comment by mefsantos** [comment]
> Thanks for that but please create a pull request so that we can merge your changes ;)

I figured how to do the pull request. Done already :)

**Comment by bastianraschke** [comment]
Thanks for your PR @mefsantos, i close the issue and we will review the PR later.
