### ISSUE TITLE
The received packet do not begin with a valid header! for Raspberry pi 3b +

### ISSUE THREAD

**Issue by jainal09** [bastianraschke/pyfingerprint#71]
Hi, I am using a UART to USB Converter for connecting the fingerprint sensor with my raspberry pi and below is the code which I have changed for my use.

The extra hardware I am using is OLED DISPLAY & 3*4 matrix keypad.
https://gist.github.com/jainal09/db4074a4bd1107cc7f527ee51014855a

I am running example_search.py in such a way that after a successful attempt i am calling the script again through :
`os.system("python search.py"`)
Here search.py is my script name.
The Scripts runs fine for 4-5 times in infinite loop but after that, it pops up an exception 
The received packet do not begin with a valid header! 
The fingerprint sensor could not be initialized!

Re-Running the script fixes error but on the 4-5 attempt again I am getting the error.
Please Help!
It will be a great relief if you help me solve this issue:)

**Comment by jainal09** [comment]
Hi please help me its kind of like urgent as a whole project is depending on this thing!!

**Comment by bastianraschke** [comment]
First, why you call the python code via the system command? Why not call direct your function or whatever - this does not make sense for me and adds unnecessary overhead.

It seems, the communication failed: Try to reduce the baudrate and/or use another converter and/or add some delay time after each loop. Also see FAQ #1 on https://sicherheitskritisch.de/2015/03/fingerprint-sensor-fuer-den-raspberry-pi-und-debian-linux-en/

**Comment by bastianraschke** [comment]
I close the issue because of missing information updates.
