### ISSUE TITLE
example_enroll.py not finding finger

### ISSUE THREAD

**Issue by Siddapa** [bastianraschke/pyfingerprint#72]
Once I run the .py file, my fingerprint sensor doesn't sense my finger. I have a FlashTree FMP12 and am aware that it isn't on the list of compatible sensors, but I saw a guide with this same sensor working with this module, Can anyone tell me what's wrong?

**Comment by philippmeisberger** [comment]
Could you please provide the link to this guide? Do you have a datasheet? Please describe what you want to achieve and what you have tried yet.

**Comment by Siddapa** [comment]
I figured out why it doesn't work. The sensor was built for an Arduino. This means that the raspberrypi can't read the data given by the Arduino. I found the correct GitHub repository for it, but it uses .ino files. Thx anyway
