### ISSUE TITLE
Unable to initialize fingerprint sensor

### ISSUE THREAD

**Issue by r-valle** [bastianraschke/pyfingerprint#73]
Hi I am having some issue using the library when I try to connect a fingerprint sensor with an Arduino One board.

I want to try some examples, but I don't manage to make any of them work correctly. (I have tried the index and enroll examples)

I have tried to switch the green and the white wire, but I get the same error.

The error is the following one: **The received packet do not begin with a valid header!**

I am sure that the board and the sensor work correctly because I have tried them using Arduino IDE (I have executed several examples using the same board, sensor and wires without any error)

As far as I have reviewed, the error seems to happen when trying to close the connection at the __del__() method.

![Captura de pantalla -2019-04-29 15-35-19](https://user-images.githubusercontent.com/9446614/56901786-3c8e2580-6a99-11e9-9afe-49b27e156695.png)

I would like to know how I can find out which headers are valid. 

I have changed the port '/dev/ttyUSB0' because it doesn't exist, so I use the port '/dev/ttyACM0'. 
(I am sure this port does exist and it's available because I run the command 'python3 -m serial.tools.list_ports' and it displays that this port is available.)

How I connect the board with the sensor:

![IMG_20190429_154355](https://user-images.githubusercontent.com/9446614/56901601-d6a19e00-6a98-11e9-9db7-a580c8365533.jpg)

![IMG_20190429_154420](https://user-images.githubusercontent.com/9446614/56901631-e4efba00-6a98-11e9-9956-2371d9b06959.jpg)

I think that this issue can happen due to the sensor doesn't send any data when it has to send the sensor's password. I have debugged the code using PyCharm and I have noticed that in the method __readPacket() the packet data is null, so the condition at the line 300 is always True:

The receivedPacketData variable is null: [b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'']

![Captura de pantalla -2019-04-29 16-15-39](https://user-images.githubusercontent.com/9446614/56902244-2896f380-6a9a-11e9-9fdd-c03133122524.png)

Also, I would like anyone to confirm that the sensor is compatible with this library.

Platform details:
Python 3.5
Debian 9.7 64 bits
Arduino Uno board
Fingerprint sensor module for Mega2560 UNO R3 51 AVR STM32 DC3.8-7V

https://www.amazon.es/gp/product/B07G383YK2/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

Manual: https://www.adrive.com/public/dJ6NgF/F0001228%2040Optical%20Fingerprint%20Module%20User's%20Manual.pdf

Thanks in advance. Any help is welcome.

**Comment by bastianraschke** [comment]
You said, you tested the sensor with the Arduino on the pictures and it worked, but not with PyFingerprint? You tested the same methods? Same setup (baud rate, password etc.)? Which library and version did you used for the Arduino test?

**Comment by r-valle** [comment]
> You said, you tested the sensor with the Arduino on the pictures and it worked, but not with PyFingerprint? You tested the same methods? Same setup (baud rate, password etc.)? Which library and version did you used for the Arduino test?

Thank for answering, but I am not working in this project anymore, so you can close this issue.
