### ISSUE TITLE
DownloadImage 

### ISSUE THREAD

**Issue by rajtan** [bastianraschke/pyfingerprint#74]
In the dev branch https://github.com/bastianraschke/pyfingerprint/blob/5c9bc7a7ee8df1dc3451d227efe3728399b3eb6c/src/files/pyfingerprint/pyfingerprint.py

Lines 839-840 results in error (raised by PIL Image module)

Following lines result in the correct operation.

	(resultImageWidth, resultImageHeight) = resultImage.size

        for y in range(resultImageHeight):
            for x in range(resultImageWidth):

Bascially, calling the method size of Image object to get the tuple of width and height and then using these in the interative loops

**Comment by bastianraschke** [comment]
Thanks for the issue report. Merged it.
