### ISSUE TITLE
Unable to debuild

### ISSUE THREAD

**Issue by rubiagatra** [bastianraschke/pyfingerprint#8]
I can't debuild the src and it has output like this 

` dpkg-buildpackage -rfakeroot -D -us -uc
dpkg-buildpackage: source package python-fingerprint
dpkg-buildpackage: source version 1.4
dpkg-buildpackage: source distribution stable
dpkg-buildpackage: source changed by Philipp Meisberger <team@pm-codeworks.de>
 dpkg-source --before-build src
dpkg-buildpackage: host architecture amd64
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper (>= 9)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed`

what kind of dependencies I should install?

**Comment by philippmeisberger** [comment]
Which OS are you using?

**Comment by rubiagatra** [comment]
I am using Ubuntu 16.04.2 64 bit . Does it works with ubuntu? and I tried to install to raspberry pi 3 and I got this error when use `debuild`

`Now signing changes and any dsc files...
 signfile python-fingerprint_1.4.dsc Philipp Meisberger <team@pm-codeworks.de>
gpg: directory '/home/pi/.gnupg' created
gpg: new configuration file '/home/pi/.gnupg/gpg.conf' created
gpg: WARNING: options in '/home/pi/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring '/home/pi/.gnupg/secring.gpg' created
gpg: keyring '/home/pi/.gnupg/pubring.gpg' created
gpg: skipped "Philipp Meisberger <team@pm-codeworks.de>": secret key not available
gpg: /tmp/debsign.AAYsWuaI/python-fingerprint_1.4.dsc: clearsign failed: secret key not available
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1295:
running debsign failed` 
 
and I succesfully built the deb package using this command

`dpkg-buildpackage -uc -us`

**Comment by philippmeisberger** [comment]
Of course it works on Ubuntu. The second error you pasted is usual as debsign tries to sign the package with a the GPG key of the maintainer. 

Nice to know that `dpkg-buildpackage -uc -us` is the correct command for building the package as non-maintainer. @bastianraschke should mention that in the readme ;)

**Comment by rubiagatra** [comment]
Can I ask something @philippmeisberger ? Is this library works with PFM10 and R305 fingerprint module?

**Comment by philippmeisberger** [comment]
I checked the specifications and yes the R305 fingerprint module should work but the PFM10 will not

**Comment by rubiagatra** [comment]
Thank you @philippmeisberger it is works on R305. :smile:

**Comment by EsEm17** [comment]
We have encountered this error:
Operation failed!
Exception message: storeTemplate() takes at least 2 arguments (1given)
Can you help us out? Pleease. Thank you.
