### ISSUE TITLE
Won't run in Virtual Environment

### ISSUE THREAD

**Issue by geokscott** [bastianraschke/pyfingerprint#82]
I have successfully installed and built the code on a Pi and installed the python3-fingerprint 1.5 version.  It runs fine with python 3, but when I try to run it in a python3 virtual environment I get:

 from pyfingerprint.pyfingerprint import PyFingerprint
ModuleNotFoundError: No module named 'pyfingerprint'

**Comment by philippmeisberger** [comment]
We uploaded the package to PyPi. Please try again with this package.

**Comment by geokscott** [comment]
Awesome thank you, works great!!!!
