### ISSUE TITLE
Unable to install on Raspberry Pi

### ISSUE THREAD

**Issue by yanickrochon** [bastianraschke/pyfingerprint#87]
The command : `mk-build-deps -i debian/control` fails with `W: Unable to locate package debian/control`. I have uncommented the `deb-src`, and updated the catalog, but nothing works.

I am seeing others using this on Raspberry Pi's, so it would be nice to have some documentation in the README about this.

**Comment by philippmeisberger** [comment]
Hi. This command must be executed from the `src` directory like documented in the README ;)

**Comment by bastianraschke** [comment]
I close the issue, because it should be resolved.
