### ISSUE TITLE
readPacket function does not handle case were no byte is read

### ISSUE THREAD

**Issue by chrisb2** [bastianraschke/pyfingerprint#96]
At [L315](https://github.com/bastianraschke/pyfingerprint/blob/Development/src/files/pyfingerprint/pyfingerprint.py#L315) in the __readPacket() function a check is made that a byte has been received, but the case where it not received is not handled. I believe the code should look like this:
```
            if ( len(receivedFragment) != 0 ):
                receivedFragment = self.__stringToByte(receivedFragment)
                ## print 'Received packet fragment = ' + hex(receivedFragment)
            else:
                continue
```
With the current code, if no byte is read an exception with the following message is raise:
> The received packet do not begin with a valid header!

Happy to raise a PR for this is you like.

regards,
Chris

**Comment by philippmeisberger** [comment]
Hi @chrisb2 ,
this could may fix a really annoying bug which we are struggling for years ;) I will create a fix for that!

**Comment by philippmeisberger** [comment]
Should be fixed. Therefore I close this issue.
