### ISSUE TITLE
exit status 2 error

### ISSUE THREAD

**Issue by snappercayt** [bastianraschke/pyfingerprint#97]
was installing it on raspberry pi 3 using the steps on the [`pyfingerprint github page`](https://github.com/bastianraschke/pyfingerprint) then at this step 
> dpkg-buildpackage -uc -us

gave the following error

> Extension error:
Unknown event name: autodoc-process-docstring
debian/rules:15: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 1
make[1]: Leaving directory '/home/pi/pyfingerprint/src'
debian/rules:6: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by philippmeisberger** [comment]
It seems that there is a missing dependency... Hard to guess which is missing.
Did you install all the required build dependencies?

**Comment by snappercayt** [comment]
I did run the commands in the sequence it was given, I hope all the dependencies were Installed like that.
If not then how do I find which ones are missing?

**Comment by philippmeisberger** [comment]
OK. Hard to guess which are missing... 
Anyway, I am hosting an APT repository which contains pre build PyFingerprint Debian package. Here is the setup how to add it: https://www.pm-codeworks.de/pages/apt-repository-en.html.

After that you can install PyFingerprint by this command: `apt install python3-fingerprint`

**Comment by snappercayt** [comment]
that is interesting thank you so much, that would be helpful for those who want to start it with that 

edit 1:
so I tried to add the PM codeworks package but didn't add to the list
I just did `apt install python3-fingerprint` and it added it with some error

edit 2: 
my code wasn't working with python3 before, now it works with that too
thanks to @philippmeisberger for the prebuild package
